version: "2"
services:
  piadas:
    build: ./listaPiadas
    ports:
      - 7000:7000
  comentarios:
    build: ./listaComentarios
    ports:
      - 5000:5000
  frontapp:
    build: ./frontapp
    ports:
      - 8080:8080
