version: "2"
services:
  piadas:
    build: ./listaPiadas
  comentarios:
    build: ./listaComentarios
  frontapp:
    build: ./frontapp
  nginx:
    build: ./nginx
    links:
      - piadas
      - comentarios
      - frontapp
    ports:
      - 80:80
    volumes:
      - ./:/vol
volumes:
  vol: